// ============================================================================
// IRONMAP · scripts · build-web
// Emits app/ironmap-data.js — a browser global (window.IRONMAP) carrying the
// real catalog counts + a program precomputed by the Node engines, so the
// prototype displays genuine engine output instead of hard-coded fakes.
// `npm run build:web`.
// ============================================================================

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { counts, machines, exercises, dietModes } from "../packages/core/data.mjs";
import { buildProgram } from "../packages/core/program.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const demo = buildProgram(
  { weightKg: 82, heightCm: 178, age: 29, sex: "male", bodyFatPct: 0.18, segmental: { leftArmKg: 3.6, rightArmKg: 3.85 } },
  { goal: "recomp", daysPerWeek: 4, minutesPerSession: 60, dietMode: "mid_healthy",
    availableMachines: machines.filter((m) => m.category !== "cardio").slice(0, 20).map((m) => m.slug), locale: "en" }
);

const payload = {
  version: demo.engineVersion,
  counts,
  dietModes: dietModes.map((d) => ({ id: d.id, label: d.label, label_ar: d.label_ar })),
  machines: machines.map((m) => ({ slug: m.slug, name: m.name, name_ar: m.name_ar, category: m.category })),
  exercises: exercises.map((e) => ({ slug: e.slug, name: e.name, machine: e.machine, pattern: e.pattern })),
  demoProgram: demo,
};

const js = `// GENERATED by scripts/build-web.mjs — do not hand-edit. Real engine output.
window.IRONMAP = ${JSON.stringify(payload)};
`;
writeFileSync(join(ROOT, "app", "ironmap-data.js"), js);
console.log(`wrote app/ironmap-data.js — ${counts.machines} machines, ${counts.exercises} exercises, 1 precomputed program (${Math.round(js.length / 1024)} KB)`);
