// ============================================================================
// IRONMAP · scripts · gen-sql
// Reads /data/*.json (single source of truth) and emits sql/100_seed_gym.sql
// with INSERTs matching the 001 schema. `npm run gen`. Never hand-edit the
// generated file — change the JSON and regenerate.
// ============================================================================

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const load = (f) => JSON.parse(readFileSync(join(ROOT, "data", f), "utf8"));

// ---- SQL literal helpers ---------------------------------------------------
const q = (s) => (s === null || s === undefined ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const n = (x) => (x === null || x === undefined ? "null" : String(x));
const b = (x) => (x ? "true" : "false");
const arr = (a) => (!a || !a.length ? "'{}'" : `array[${a.map(q).join(",")}]`);
const j = (o) => (o === null || o === undefined ? "null" : `'${JSON.stringify(o).replace(/'/g, "''")}'::jsonb`);

function insert(table, cols, rows, conflict) {
  if (!rows.length) return "";
  const head = `insert into ${table} (${cols.join(", ")}) values`;
  const body = rows.map((r) => "  (" + r.join(", ") + ")").join(",\n");
  const tail = conflict ? `\non conflict ${conflict};` : ";";
  return `${head}\n${body}${tail}\n\n`;
}

const cats = load("machines.json").categories;
const machines = load("machines.json").machines;
const fvs = load("force_vectors.json").force_vectors;
const muscles = load("muscles.json").muscles;
const exercises = load("exercises.json").exercises;
const diets = load("diet_modes.json").diet_modes;
const foods = load("foods.json").foods;
const stages = load("coaching.json").coaching_stages;
const config = load("config.json");

let out = `-- ============================================================================
-- IRONMAP · 100 · gym seed  (GENERATED by scripts/gen-sql.mjs — do not hand-edit)
-- Source: /data/*.json. Regenerate with: npm run gen
-- ============================================================================

`;

out += insert("gym.equipment_categories", ["id", "label", "label_ar"],
  cats.map((c) => [q(c.id), q(c.label), q(c.label_ar)]), "(id) do nothing");

out += insert("gym.force_vectors", ["id", "label", "plane", "description", "example"],
  fvs.map((v) => [q(v.id), q(v.label), q(v.plane), q(v.description), q(v.example)]), "(id) do nothing");

out += insert("gym.muscles", ["id", "label", "label_ar", "region", "muscle_group", "is_prime", "landmarks"],
  muscles.map((m) => [q(m.id), q(m.label), q(m.label_ar), q(m.region), q(m.group), b(m.prime), j(m.landmarks)]),
  "(id) do nothing");

out += insert("gym.machine_types",
  ["slug", "canonical_name", "name_ar", "category_id", "superclass", "primary_force", "primary_muscles", "secondary_muscles", "fgvc_cues", "confused_with", "tutorial_ref"],
  machines.map((m) => [q(m.slug), q(m.name), q(m.name_ar), q(m.category), q(m.superclass), q(m.primary_force),
    arr(m.primary_muscles), arr(m.secondary_muscles), j(m.fgvc_cues || null), arr(m.confused_with), q(m.tutorial_ref)]),
  "(slug) do nothing");

out += insert("gym.exercises",
  ["slug", "name", "name_ar", "machine_type_slug", "force_vector", "movement_pattern", "grip", "trunk", "difficulty", "is_unilateral", "cues", "contraindications"],
  exercises.map((e) => [q(e.slug), q(e.name), q(e.name_ar), q(e.machine), q(e.vector), q(e.pattern), q(e.grip), q(e.trunk),
    n(e.difficulty), b(e.unilateral), j(e.cues || null), arr(e.contra)]),
  "(slug) do nothing");

const activationRows = exercises.flatMap((e) =>
  e.activation.map((a) => [q(e.slug), q(a.m), q(a.role), q(a.band), n(a.w), n(a.mvic_low), n(a.mvic_high)]));
out += insert("gym.exercise_muscle_activation",
  ["exercise_slug", "muscle_id", "role", "band", "activation", "mvic_low", "mvic_high"],
  activationRows, "(exercise_slug, muscle_id) do nothing");

const meRows = Object.entries(config.metabolic_equations).map(([id, m]) =>
  [q(id), q(id.replace(/_/g, " ")), q(m.basis), q(m.margin_err), j(m.coeffs), q(m.note || null)]);
out += insert("gym.metabolic_equations", ["id", "label", "basis", "margin_err", "coeffs", "note"], meRows, "(id) do nothing");

out += insert("gym.diet_modes",
  ["id", "label", "label_ar", "protein_pct", "fat_pct", "carb_pct", "protein_g_per_kg_lbm", "rules", "basis"],
  diets.map((d) => [q(d.id), q(d.label), q(d.label_ar), n(d.protein), n(d.fat), n(d.carbs), n(d.protein_per_kg_lbm), j(d.rules), q(d.basis)]),
  "(id) do nothing");

out += insert("gym.foods",
  ["source", "name", "name_ar", "kcal_100g", "protein_100g", "carbs_100g", "fat_100g", "fiber_100g", "nova_class", "tags"],
  foods.map((f) => [q(f.source), q(f.name), q(f.name_ar), n(f.kcal_100g), n(f.protein_100g), n(f.carbs_100g), n(f.fat_100g), n(f.fiber_100g), n(f.nova), arr(f.tags)]),
  null);

out += insert("gym.coaching_stages", ["id", "ordinal", "label", "label_ar", "technique", "strategy"],
  stages.map((s) => [q(s.id), n(s.ordinal), q(s.label), q(s.label_ar), q(s.technique), q(s.strategy)]), "(id) do nothing");

const configRows = Object.entries(config)
  .filter(([k]) => k !== "_source" && k !== "metabolic_equations")
  .map(([k, v]) => [q(k), j(v)]);
out += insert("gym.config", ["key", "value"], configRows, "(key) do update set value = excluded.value, updated_at = now()");

writeFileSync(join(ROOT, "sql", "100_seed_gym.sql"), out);
const rowCount = cats.length + fvs.length + muscles.length + machines.length + exercises.length +
  activationRows.length + meRows.length + diets.length + foods.length + stages.length + configRows.length;
console.log(`wrote sql/100_seed_gym.sql — ${rowCount} rows across 11 tables`);
