-- ============================================================================
-- IRONMAP · 001 · gym schema (canonical knowledge, DDL only)
-- The global layer shared by every tenant: equipment taxonomy, biomechanics,
-- nutrition science, coaching/vision config. Read for any authenticated user,
-- written only by service-role. Column shapes match /data/*.json exactly; the
-- seed INSERTs are generated by scripts/gen-sql.mjs → 100_seed_gym.sql.
-- Target: Postgres 16 + Supabase (roles: authenticated, service_role).
-- ============================================================================

create schema if not exists gym;
create extension if not exists vector;

create table gym.equipment_categories ( id text primary key, label text not null, label_ar text );

create table gym.force_vectors ( id text primary key, label text not null, plane text not null, description text, example text );

create table gym.muscles (
  id text primary key, label text not null, label_ar text,
  region text not null, muscle_group text, is_prime boolean not null default true,
  landmarks jsonb
);
create index on gym.muscles (region);

create table gym.machine_types (
  slug text primary key, canonical_name text not null, name_ar text,
  category_id text not null references gym.equipment_categories(id),
  superclass text not null,
  primary_force text references gym.force_vectors(id),
  primary_muscles text[] not null default '{}',
  secondary_muscles text[] not null default '{}',
  fgvc_cues jsonb, confused_with text[] not null default '{}',
  tutorial_ref text, embedding vector(1536),
  created_at timestamptz not null default now()
);
create index on gym.machine_types (category_id);
create index on gym.machine_types (superclass);

create table gym.exercises (
  slug text primary key, name text not null, name_ar text,
  machine_type_slug text references gym.machine_types(slug),
  force_vector text references gym.force_vectors(id),
  movement_pattern text not null, grip text, trunk text,
  difficulty int not null default 1, is_unilateral boolean not null default false,
  cues jsonb, contraindications text[] not null default '{}',
  created_at timestamptz not null default now()
);
create index on gym.exercises (movement_pattern);

create table gym.exercise_muscle_activation (
  exercise_slug text not null references gym.exercises(slug) on delete cascade,
  muscle_id text not null references gym.muscles(id),
  role text not null, band text not null,
  activation numeric(3,2) not null, mvic_low int, mvic_high int,
  primary key (exercise_slug, muscle_id)
);

create table gym.metabolic_equations (
  id text primary key, label text not null, basis text not null,
  margin_err text, coeffs jsonb not null, note text
);

create table gym.diet_modes (
  id text primary key, label text not null, label_ar text,
  protein_pct numeric(3,2), fat_pct numeric(3,2), carb_pct numeric(3,2),
  protein_g_per_kg_lbm numeric(3,1), rules jsonb not null, basis text
);

create table gym.foods (
  id uuid primary key default gen_random_uuid(),
  source text not null, fdc_id bigint, name text not null, name_ar text,
  kcal_100g numeric(6,1) not null, protein_100g numeric(5,1) not null,
  carbs_100g numeric(5,1) not null, fat_100g numeric(5,1) not null, fiber_100g numeric(5,1),
  nova_class int, tags text[] not null default '{}', embedding vector(1536),
  updated_at timestamptz not null default now()
);
create index on gym.foods using gin (tags);

create table gym.coaching_stages (
  id text primary key, ordinal int not null, label text not null, label_ar text,
  technique text not null, strategy text not null
);

create table gym.config (
  key text primary key, value jsonb not null, updated_at timestamptz not null default now()
);

-- ---- RLS: read for authenticated, write via service-role (bypasses RLS) ----
do $$
declare t text;
begin
  foreach t in array array[
    'equipment_categories','force_vectors','muscles','machine_types','exercises',
    'exercise_muscle_activation','metabolic_equations','diet_modes','foods',
    'coaching_stages','config'
  ] loop
    execute format('alter table gym.%I enable row level security;', t);
    execute format('create policy read_authenticated on gym.%I for select to authenticated using (true);', t);
  end loop;
end $$;
